---
title: Research
---

**Chiumenti, Nicholas.** 2022. [*Evictions in New England and the Impact of Public Policy.*](https://www.bostonfed.org/publications/new-england-public-policy-center-regional-briefs/2022/evictions-in-new-england-and-the-impact-of-public-policy-during-the-covid19-pandemic.aspx) Regional Brief 22-2. Federal Reserve Bank of Boston, New England Public Policy Center. Boston, MA.

<details>
  <summary>**Show Abstract:**</summary>
> To stave off a flood of evictions during the COVID-19 pandemic, which was the feared outcome when millions of renting households were suddenly unemployed, Congress and many states implemented policies that included eviction moratoriums and federally funded rental-assistance programs. These programs succeeded in keeping millions of renters housed and driving eviction rates down in the early months of the pandemic. The number of evictions filed in New England declined 56 percent in 2020 and 39 percent in 2021 compared with the average number of evictions filed annually from 2017 through 2019—the pre-pandemic period. Recently, new fears have arisen that many renters remain financially unstable from the pandemic and that a dramatic increase in the number of evictions will follow the end of rental-assistance programs. Based on data from three New England states, it is not clear that these fears will be realized. Evictions rose modestly following the end of these programs in Massachusetts and Rhode Island but stayed below pre-pandemic levels. While in Connecticut, evictions spiked sharply once programs ended and remain slightly above pre-pandemic levels.
</details>

[{{< bi filetype-pdf >}} PDF](assets/papers/neppcrb2202.pdf) &emsp; [{{< bi link-45deg >}} SSRN](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4307463)


Sood, Aradhya, Amrita Kulka, Nicholas Chiumenti. (forthcoming). How to Increase Housing Affordability? Understanding Local Deterrents to Building Multifamily Housing. Working Paper Series. Federal Reserve Bank of Boston, New England Public Policy Center. Boston, MA.

**Chiumenti, Nicholas.** 2021. How the COVID-19 Pandemic Changed Household Migration in New England. Regional Brief 2021-3. Federal Reserve Bank of Boston, New England Public Policy Center. Boston, MA.

**Chiumenti, Nicholas.** 2021. Rental Affordability and COVID-19 in Rural New England. Regional Brief 2021-1. Federal Reserve Bank of Boston, New England Public Policy Center. Boston, MA.

**Chiumenti, Nicholas.** 2020. Impact of the COVID-19 Pandemic on New England Homeowners and Renters. Regional Brief 2020-2. Federal Reserve Bank of Boston, New England Public Policy Center. Boston, MA.

**Chiumenti, Nicholas.** 2020. Recent Trends in Residential Segregation in New England. Regional Brief 2020-1. Federal Reserve Bank of Boston, New England Public Policy Center. Boston, MA.

Zhao, Bo and **Chiumenti, Nicholas.** 2020. Measuring Disparities in Cost and Spending across Connecticut School Districts. Research Report 2020-2. Federal Reserve Bank of Boston, New England Public Policy Center. Boston, MA.

**Chiumenti, Nicholas.** 2019. The Growing Shortage of Affordable Housing for the Extremely Low Income in Massachusetts. Policy Report 2019-1. Federal Reserve Bank of Boston, New England Public Policy Center. Boston, MA.

**Chiumenti, Nicholas.** 2018. The Supply of Permanent Supportive Housing in Massachusetts: Comparing Availability to the Chronic Homeless Population. Federal Reserve Bank of Boston, New England Public Policy Center. Boston, MA.

Henry, David K., Sandra D. Cooke-Hull, Jacqueline Savukinas, Alis Asadurian, **Chiumenti, Nicholas.** 2017. Estimating the Investment and Job Creation Impact of the EB-5 Program. U.S. Department of Commerce, Economics and Statistics Administration, Office of the Chief Economist. Washington, D.C. 
